#httpd_server_admin: bert@linuxlab.lan
#httpd_listen: 8080
---

#--firewall-----------------------------#
rhbase_firewall_allow_services:
  - samba
#-------------------------------#

rhbase_user_groups:
  - IT-Administratie
  - Verkoop
  - Administratie
  - Ontwikkeling
  - Directie 

samba_load_homes: true

#--users-----------------------------#
rhbase_users: 
  - name: Joa
    comment: 'Joa'
    password: '!!'
    shell: /sbin/nologin
    groups: 
      - IT-Administratie
  - name: Max
    comment: 'Max'
    password: YOKB.qTipuJSA
    groups: 
      - IT-Administratie
      - Verkoop
      - Administratie
      - Ontwikkeling
      - Directie


samba_users:
  - name: Joa
    password: felix
  - name: Max
    password: payne

samba_shares:
  - name: IT-Administratie
    group: IT-Administratie
    valid_users: +IT-Administratie
    write_list: +IT-Administratie
  - name: Verkoop
    group: Verkoop
    valid_users: +Verkoop
  - name: Administratie
    group: Administratie
    valid_users: +Administratie
  - name: Ontwikkeling
    group: Ontwikkeling
    valid_users: +Ontwikkeling
  - name: Directie
    group: Directie
    valid_users: +Directie



#-------------------------------#

